### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by aniruddhamx2020** [GUR9000/UG-RNNN_TF#1]
**Original save, restore code as given**:
**Save**:
`def save_model(self, sess, checkpoint_dir, step):
    saver = tf.train.Saver(self.trainable_variables, max_to_keep=1) 
    checkpoint_file = os.path.join(checkpoint_dir, 'model.ckpt')
    saver.save(sess, save_path=checkpoint_file)`

**Restore**:
`def restore_model(self, sess, checkpoint_dir):
    saver = tf.compat.v1.train.Saver(self.trainable_variables)
    saver.restore(sess, tf.compat.v1.train.latest_checkpoint(checkpoint_dir))`

**Problem faced during execution**:

INFO:tensorflow:Restoring parameters from ./data/DILI/Model_Train_DILI_Data\default_model\model.ckpt I0805 17:57:37.460012 3052 saver.py:1284] Restoring parameters from ./data/DILI/Model_Train_DILI_Data\default_model\model.ckpt 2020-08-05 17:57:37.489041: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key 0x000001AED262B208EncodingNN/hidden1/biases not found in checkpoint Traceback (most recent call last): File "C:\Users\e099250\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call return fn(*args) File "C:\Users\e099250\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn target_list, run_metadata) File "C:\Users\e099250\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun run_metadata) tensorflow.python.framework.errors_impl.NotFoundError: Key 0x000001AED262B208EncodingNN/hidden1/biases not found in checkpoint [[{{node save/RestoreV2}}]]

**_Tried by self_**:

`def restore_model(self, sess, checkpoint_dir):
    saver = tf.compat.v1.train.Saver(self.trainable_variables)
    saver.restore(sess, tf.compat.v1.train.latest_checkpoint(checkpoint_dir))`

**_Error_**: All the test prediction are being same. I assume, it restored the graph. But failed to restore the parameters.

**Comment by GUR9000** [comment]
It looks like a new tensorflow issue - what version are you using?
